---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
        name: Check yaml files
      - id: trailing-whitespace
        name: Check trailing whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.36.2
    hooks:
      - id: yamllint
        name: Check yaml files (yamllint)
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v25.1.3
    hooks:
      - id: ansible-lint
        name: Check ansible files (ansible-lint)
        # https://github.com/ansible/ansible-lint/issues/1066
        always_run: false
        # args: ["-x", "602"]
        exclude_types: [markdown, shell]
        types: [yaml]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: Checks for common misspellings in text files
        entry: codespell
        language: python
  - repo: local
    hooks:
      - id: docker-markdownlint
        name: Run markdownlint with docker
        entry: markdownlint/markdownlint -r "~MD013"
        language: docker_image
        types: [markdown]
      - id: docker-shell-shfmt
        name: Run shfmt with docker
        entry: mvdan/shfmt:v3.4.3 -d -i 2 -ci
        language: docker_image
        types: [shell]
      - id: docker-shell-lint
        name: Run shellcheck with docker
        language: docker_image
        entry: koalaman/shellcheck:stable
        types: [shell]
      - id: docker-prettier
        name: Run prettier with docker
        entry: tmknom/prettier:latest -l
        language: docker_image
        files: |
          (?x)\.(
            css|less|scss
            graphql|gql|
            html|
            js|jsx|ts|tsx|
            json|
            md|markdown|mdown|mkdn|
            mdx|
            vue|
            yaml|yml
          )$
